### ISSUE TITLE
listado de gastos

### ISSUE THREAD

**Issue by vgrana** [groupbit/gastos-mensuales#2]

**Comment by vgrana** [comment]
![WhatsApp Image 2019-07-08 at 3 56 41 PM (2)](https://user-images.githubusercontent.com/36055389/60835362-474fef80-a199-11e9-90fd-47776dd1a2dd.jpeg)
![WhatsApp Image 2019-07-08 at 3 56 41 PM (1)](https://user-images.githubusercontent.com/36055389/60835363-474fef80-a199-11e9-9349-70cb72196a98.jpeg)
![WhatsApp Image 2019-07-08 at 3 56 41 PM](https://user-images.githubusercontent.com/36055389/60835364-474fef80-a199-11e9-923e-a685d2564f31.jpeg)
![WhatsApp Image 2019-07-08 at 3 56 42 PM](https://user-images.githubusercontent.com/36055389/60835361-474fef80-a199-11e9-9f9d-2d6d1cd0b42b.jpeg)

**Comment by faloi** [comment]
Se ve lindo. Armá un pull request y lo miramos.

Vale que el PR cierre varias issues, en ese caso poné un `Closes` abajo del otro:

```
Closes #1
Closes #2
Closes #18
```
